server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
mybatis:
  type-aliases-package: com.xcy.recruitmentsystem.pojo
  mapper-locations: classpath:mapper/*.xml


